### ISSUE TITLE
TypeError when multigpu train

### ISSUE THREAD

**Issue by zhengjiawen** [yu20103983/FOTS#11]
Traceback (most recent call last):                                                             
  File "multigpu_train.py", line 221, in <module>                                              
    tf.app.run()                                                                               
  File "/data/home/zjw/anaconda3/envs/tf-py27/lib/python2.7/site-packages/tensorflow/python/pla
tform/app.py", line 48, in run                                                                 
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))                                         
  File "multigpu_train.py", line 113, in main                                                  
    models.append(build_model(opt, reuse_variables, scope))                                    
  File "multigpu_train.py", line 76, in build_model                                            
    fots = FOTS_trainModel(input_images, input_brboxes, reuse_variables)                       
  File "/data/home/zjw/pythonFile/FOTS-1/FOTS/fots_trainModel.py", line 22, in __init__        
    self.rg = recognizer.recognizer(self.rois, self.ws, NUM_CLASSES, FLAGS.keepProb, is_trainin
g=True)                                                                                        
  File "/data/home/zjw/pythonFile/FOTS-1/FOTS/recognizer.py", line 19, in __init__             
    self.convLayers(weight_decay, is_training)                                                 
  File "/data/home/zjw/pythonFile/FOTS-1/FOTS/recognizer.py", line 63, in convLayers           
    self.word_vec = tf.transpose(tf.reshape(x, (-1, x.shape[2], x.shape[3])), (1, 0, 2))       
  File "/data/home/zjw/anaconda3/envs/tf-py27/lib/python2.7/site-packages/tensorflow/python/op
/gen_array_ops.py", line 2619, in reshape                                                     
    name=name)                                                                                 
  File "/data/home/zjw/anaconda3/envs/tf-py27/lib/python2.7/site-packages/tensorflow/python/fra
mework/op_def_library.py", line 493, in apply_op                                               
    raise err                                                                                  
TypeError: Failed to convert object of type <type 'tuple'> to Tensor. Contents: (-1, Dimension(
64), Dimension(128)). Consider casting elements to a supported type.

=============================================================
The problem occurs when I train in ICDAR2015, can anyone help to fix it?
Thanks a lot.

**Comment by Marscep** [comment]
do you fix it?  I am struggling in it too.
