### ISSUE TITLE
NotFoundError: dataFolder/FOST_textOnPlate

### ISSUE THREAD

**Issue by AndosonLiu** [yu20103983/FOTS#14]
你好：
我已经在`FOTS/dataset/dataReader.py`中配置了ICDAR2015 *4.4_end_to_end*的训练数据：
![error_nosuchdir](https://user-images.githubusercontent.com/9996308/58924899-28180980-8778-11e9-9c99-9119b1c1a417.jpg)
但是运行`python multigpu_train.py 0`训练，还是会报错：
`Traceback (most recent call last):
  File "multigpu_train.py", line 221, in <module>
    tf.app.run()
  File "/home/gust01/.conda/envs/tensorflow_py2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "multigpu_train.py", line 93, in main
    tf.gfile.MkDir(FLAGS.checkpoint_path)
  File "/home/gust01/.conda/envs/tensorflow_py2/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 409, in create_dir
    create_dir_v2(dirname)
  File "/home/gust01/.conda/envs/tensorflow_py2/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 427, in create_dir_v2
    pywrap_tensorflow.CreateDir(compat.as_bytes(path), status)
  File "/home/gust01/.conda/envs/tensorflow_py2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: dataFolder/FOST_textOnPlate; No such file or directory`
请问这个`dataFolder/FOST_textOnPlate`目录是在哪里配置的呢，该怎么解决呢？
谢谢你的查看！

**Comment by AndosonLiu** [comment]
上述问题已经解决：在工程的根目录下手动创建一个名为'dataFolder'的文件夹
