### ISSUE TITLE
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float64

### ISSUE THREAD

**Issue by kei6** [yu20103983/FOTS#7]
Running command: `python multi_gputrain.py`
Error:
```
Traceback (most recent call last):
  File "multigpu_train.py", line 234, in <module>
    tf.app.run()
  File "/home/ocr/miniconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "multigpu_train.py", line 230, in main
    fots_testModel.detectRecg(d_images, sess=sess)
  File "/home/ocr/FOTS/FOTS/fots_testModel.py", line 262, in detectRecg
    rois_op, ws_op = RoiRotate.RoiRotate(filter_bsharedFeatures, FLAGS.features_stride)(brotateParas)
  File "/home/ocr/FOTS/FOTS/RoiRotate.py", line 73, in __call__
    np.array(0, np.int32)])
  File "/home/ocr/miniconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 683, in scan
    maximum_iterations=n)
  File "/home/ocr/miniconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3209, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/ocr/miniconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2941, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/ocr/miniconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2878, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/ocr/miniconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3179, in <lambda> 
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/home/ocr/miniconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 662, in compute
    a_out = fn(packed_a, packed_elems)
  File "/home/ocr/FOTS/FOTS/RoiRotate.py", line 21, in scanFunc
    rotateCropedFeatures = tf.contrib.image.rotate(cropFeatures, angle)
  File "/home/ocr/miniconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/contrib/image/python/ops/image_ops.py", line 83, in rotate
    angles_to_projective_transforms(angles, image_height, image_width),
  File "/home/ocr/miniconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/contrib/image/python/ops/image_ops.py", line 142, in angles_to_projective_transforms
    angles, name="angles", dtype=dtypes.float32)
  File "/home/ocr/miniconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1011, in convert_to_tensor
    as_ref=False)
  File "/home/ocr/miniconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1107, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/ocr/miniconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 944, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float64: 'Tensor("scan/while/TensorArrayReadV3_3:0", shape=(), dtype=float64)'

```

**Comment by kei6** [comment]
I've fixed this error by: 
add `angle = tf.cast(angle, tf.float32)` into
```
    def scanFunc(self, state, b_input):
        ifeatures, outBox, cropBox, angle = b_input

        # Kei Fix
        angle = tf.cast(angle, tf.float32)

        cropFeatures = tf.image.crop_to_bounding_box(ifeatures, outBox[1], outBox[0], outBox[3], outBox[2])
        rotateCropedFeatures = tf.contrib.image.rotate(cropFeatures, angle)
```
